version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: pass
    ports: [ "5432:5432" ]
  api:
    build: ./backend
    ports: [ "8000:8000" ]
    depends_on: [ db ]
